### ISSUE TITLE
Chosen tabs are not highlighted

### ISSUE THREAD

**Issue by NikkiGetGrub** [samurailens/GGrb#1]
While switching to different tabs, Chosen tabs are not highlighted
![tabhighlight](https://cloud.githubusercontent.com/assets/27507629/25051760/e38becce-216b-11e7-9581-6f2a45408c04.png)

**Comment by SaranyaChowdary** [comment]
1. While switching to different tabs, Chosen tabs are not highlighted both(Top & Down Tab bar)
2. Clear icon is not required
3. Need to change the menu classification icons. At present icons are not relevant.

**Comment by samurailens** [comment]
@SaranyaChowdary : 
1. The bottom Tab Bar is already Highlighted. The Green/Teal color to **Home** is due to the highlighting.  _We have already mentioned in RELEASE NOTES as known issue that Top Bar is not highlighted._  

2. If Clear Icon is not required, should we put 'All'? (this was discussed in excel sheet). Let us know what you need. 

3. Yes, we are on it.
