### ISSUE TITLE
Cart item incrementation and other cart issues

### ISSUE THREAD

**Issue by SaranyaChowdary** [samurailens/GGrb#4]
1. When we try to add Combos to cart, it's not adding to the cart
2. There are couple of issues with cart mentioned in the video please do check

https://drive.google.com/file/d/0B-VY0mB4yY6mZWptemNfNEdEdXM/view?usp=sharing

**Comment by samurailens** [comment]
<img width="1440" alt="screen shot 2017-04-15 at 10 18 04 am" src="https://cloud.githubusercontent.com/assets/5208310/25060847/e725826a-21c4-11e7-9e59-27e0ef24121c.png">

Just tried it on our end, we see this issue. After adding to cart, we received response that 'Item already in cart'. hence no UI changes. I think this issue is then concerned with Server. Closing it on our end.

@SaranyaChowdary

**Comment by Hitechverma** [comment]
@samurailens If the item is already in the cart like it is showing "Item already in cart" then in UI it should show as added right? but it was not showing that too. SO it is not concerned with the server.
